config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get "home/about" => "homes#about"
  
  devise_for :users
  
  resources :users, only: [:show, :edit, :index, :update]
  
  resources :books, only: [:show, :edit, :index, :update, :create, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  validates :title,
    presence: true
    
  validates :body,
    presence: true,
    length: {maximum: 200}
    
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment,
    presence: true
    
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  
  validates :name,
    presence: true,
    uniqueness: {case_sensitive: false},
    length: {minimum: 2, maximum: 20}
    
  validates :introduction,
    length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(post_params)
    comment.book_id = book.id
    comment.save
    redirect_to request.referer
  end

  def destroy
    comment = BookComment.find(params[:id])
    if comment.user == current_user
      comment.destroy
    end
    redirect_to request.referer
  end
  
  private
  def post_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @new_book = Book.new(post_params)
    @new_book.user_id = current_user.id
    
    if @new_book.save
      flash[:notice] = "New entry is successfully created."
      redirect_to book_path(@new_book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @new_book = Book.new()
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new()
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    
    if @book.user != current_user
      redirect_to books_path
      return
    end
  end

  def update
    @book = Book.find(params[:id])
    
    if @book.user != current_user
      redirect_to book_path(@book.id)
      return
    end
    
    if @book.update(post_params)
      flash[:notice] = "The book information is successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
     
    if @book.user != current_user
      redirect_to book_path(@book.id)
      return
    end
    
    if @book.destroy
      redirect_to books_path
    else
      render :edit
    end
  end
  
  private
  
  def post_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    if !book.favorited_by?(current_user)
      favorite = current_user.favorites.new(book_id: book.id)
      favorite.save
    end
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @new_book = Book.new()
  end

  def index
    @users = User.all
    @new_book = Book.new()
  end

  def edit
    @user = User.find(params[:id])
    
    if @user != current_user
      redirect_to user_path(current_user)
      return
    end
  end

  def update
    @user = User.find(params[:id])
    
    if @user != current_user
      redirect_to user_path(current_user)
      return
    end
    
    if @user.update(user_params)
      flash[:notice] = "Your user info was successfully updated."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th style="width: 10%">
        
      </th>
      <th style="width: 20%">
        Title
      </th>
      <th>
        Opinion
      </th>
      <th style="width: 10%">
        
      </th>
      <th style="width: 20%">
        
      </th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user.id) do %>
          <%= image_tag book.user.get_profile_image(100,100) %>
        <% end %>
      </td>
      <td>
        <%= link_to book.title, book_path(book.id) %>
      </td>
      <td>
        <%= book.body %>
      </td>
      <td>
        <%= render "favorites/panel", book: book %>
      </td>
      <td>
        <%= book.book_comments.count %> comments
      </td>
      <td>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_new.html.erb
<div class="my-5">
  <h2>
    New book
  </h2>
  <%= form_with model: new_book do |f| %>
    <div class="form-group">
      <label for="newBookTitle">Title</label>
      <%= f.text_field :title, class: "form-control", id: "newBookTitle" %>
    </div>
    <div class="form-group">
      <label for="newBookOpinion">Opinion</label>
      <%= f.text_area :body, class: "form-control", id: "newBookOpinion" %>
    </div>
    <%= f.submit "Create Book", class: "btn btn-primary" %>
  <% end %>
 </div>

app/views/books/edit.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-8">
      <h2>
        Editing Book
      </h2>
      
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label for="bookTitle">Title</label>
          <%= f.text_field :title, class: "form-control", id: "bookTitle" %>
        </div>
        <div class="form-group">
          <label for="bookOpinion">Opinion</label>
          <%= f.text_field :body, class: "form-control", id: "bookOpinion" %>
        </div>
        <%= f.submit "Update Book", class: "btn btn-primary" %>
      <% end %>
      <ul>
        <li><%= link_to "Show", book_path(@book.id) %></li>
        <li><%= link_to "Back", books_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: current_user, is_current_user: true %>
      <%= render "new", new_book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render "list", books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @book.user, is_current_user: @book.user == current_user %>
      <%= render "new", new_book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              Title
            </td>
            <td>
              <%= link_to @book.title, book_path(@book.id) %>
            </td>
          </tr>
          <tr>
            <td>
              Opinion
            </td>
            <td>
              <%= @book.body %>
            </td>
          </tr>
          <tr>
            <td>
              User
            </td>
            <td>
              <%= link_to user_path(@book.user.id) do %>
                <%= image_tag @book.user.get_profile_image(100,100) %>
                <%= @book.user.name %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td>
              Likes
            </td>
            <td>
              <%= render "favorites/panel", book: @book %>
            </td>
          </tr>
          <tr>
            <td>
              Comments
            </td>
            <td>
              <div class="mb-3">
                <%= @book.book_comments.count %> comment(s)
              </div>
              
              <ul class="list-unstyled">
                <% @book.book_comments.each do |comment| %>
                  <li class="media">
                    <%= image_tag comment.user.get_profile_image(64,64) %>
                    <div class="media-body ml-2">
                      <h5 class="mt-0 mb-1">
                        <%= link_to comment.user.name, user_path(comment.user.id) %>
                        <% if current_user == comment.user %>
                          <%= link_to "Destroy", book_book_comment_path(comment.book.id, comment.id), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に削除しますか？" %>
                        <% end %>
                      </h5>
                      <%= comment.comment %>
                    </div>
                  </li>
                <% end %>
              </ul>
            </td>
          </tr>
          <tr>
            <td>
              Post Comment
            </td>
            <td>
              <%= form_with model: [@book, @book_comment] do |f| %>
                <div class="form-group">
                  <%= f.text_area :comment, class: "form-control" %>
                </div>
                <%= f.submit "送信", class: "btn btn-primary" %>
              <% end %>
            </td>
          </tr>
          <% if @book.user == current_user %>
            <tr>
              <td>
                Manage
              </td>
              <td>
                <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %>
                <%= link_to "Destroy", book_path(@book.id), class: "btn btn-sm btn-danger", method: :delete,  "data-confirm" => "本当に削除しますか？" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/favorites/_panel.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete do %>
    <i class="fas fa-heart"></i> <%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post do %>
    <i class="far fa-heart"></i> <%= book.favorites.count %>
  <% end %>
<% end %>

app/views/homes/about.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-8 mx-auto text-center">
      <h2>
        Welcome to <i class="fas fa-book" aria-hidden="true"></i>Bookers!
      </h2>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-8 mx-auto text-center">
      <h2>
        Welcome to <i class="fas fa-book" aria-hidden="true"></i>Bookers!
      </h2>
      <%= link_to "Log in", new_user_session_path, class:"btn btn-sm btn-block btn-primary" %>
      <%= link_to "Sign up", new_user_registration_path, class:"btn btn-sm btn-block btn-success" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="px-3 py-1 bg-dark">
      <nav class="navbar navbar-expand-md navbar-dark">
        <a class="navbar-brand" href="/">Bookers</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#globalNavBar" aria-controls="globalNavBar" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="globalNavBar">
          <ul class="navbar-nav ml-auto" >
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user.id), class: 'nav-link text-white' do %>
                  <i class="fas fa-home" aria-hidden="true"></i> Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path, class: 'nav-link text-white' do %>
                  <i class="fas fa-users" aria-hidden="true"></i> Users
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to books_path, class: 'nav-link text-white' do %>
                  <i class="fas fa-book-open" aria-hidden="true"></i> Books
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, class: 'nav-link text-white', method: :delete do %>
                  <i class="fas fa-sign-out-alt" aria-hidden="true"></i> logout
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to root_path, class: 'nav-link text-white' do %>
                  <i class="fas fa-home" aria-hidden="true"></i> Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to home_about_path, class: 'nav-link text-white' do %>
                  <i class="fas fa-link" aria-hidden="true"></i> About
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class: 'nav-link text-white' do %>
                  <i class="fas fa-user-plus" aria-hidden="true"></i> sign up
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: 'nav-link text-white' do %>
                  <i class="fas fa-sign-in-alt" aria-hidden="true"></i> login
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <main class="mb-auto mx-3">
      <div class="flash-notifications my-2">
        <% flash.each do |key, value| %>
          <% if key == "notice" %>
            <% cls = "notice alert alert-success" %>
          <% else %>
            <% cls = "error alert alert-danger" %>
          <% end %>
         <%= content_tag(:div, value, class: cls) %>
        <% end %>
        <% [@new_book, @user, @book].each do |edit_target| %>
          <% if edit_target and  edit_target.errors.any? %>
            <div class="error alert alert-danger">
              <%= edit_target.errors.count %> error(s) occurred.
              <ul>
                <% edit_target.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        <% end %>
      </div>
      <%= yield %>
    </main>
    <footer class="bg-dark text-white p-3 text-right">
      © 2023 shimizu toma
    </footer>
  </body>
</html>

app/views/users/_info.html.erb
<div class="row">
  <h2>
    User info
  </h2>
</div>
<div class="row">
  <%= image_tag user.get_profile_image(100,100) %>
  
  <table class="table">
    <tbody>
      <tr>
    	  <th>
    	    name
        </th>
    	  <th>
    	    <%= user.name %>
        </th>
      </tr>
      <tr>
    	  <th>
    	    introduction
        </th>
    	  <th>
    	    <%= user.introduction %>
    	  </th>
      </tr>
    </tbody>
  </table>
</div>
<div class="row">
  <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-8">
      <h2>
        User info
      </h2>
      
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <label for="userName">Name</label>
          <%= f.text_field :name, class: "form-control", id: "userName" %>
        </div>
        <div class="form-group">
          <label for="userImage">Image</label>
          <%= f.file_field :profile_image, class: "form-control-file", id: "userImage" %>
        </div>
        <div class="form-group">
          <label for="userIntro">Introduction</label>
          <%= f.text_field :introduction, class: "form-control", id: "userIntro" %>
        </div>
        <%= f.submit "Update User", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: current_user, is_current_user: true %>
      <%= render "books/new", new_book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>
              image
            </th>
            <th>
              name
            </th>
            <th colspan="3">
              
            </th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= image_tag user.get_profile_image(100,100) %>
            </td>
            <td>
              <%= link_to user.name, user_path(user.id) %>
            </td>
            <td>
              <%= link_to "Show", user_path(user.id) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "info", user: @user, is_current_user: @user == current_user %>
      <%= render "books/new", new_book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render "books/list", books: @user.books %>
    </div>
  </div>
</div>